In [2]:
# 安装NumPy
%pip install numpy -U

# 导入模块（遵循PDF推荐的简写规范）
import numpy as np

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Note: you may need to restart the kernel to use updated packages.


In [3]:
# 1. 从列表/元组创建（array函数）
arr1 = np.array([1, 2, 3, 4, 5])  # 一维数组
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  # 二维数组
arr3 = np.array(((1, 2), (3, 4)), dtype=np.float32)  # 指定数据类型

print("arr1（一维数组）:", arr1)
print("arr2（二维数组）:\n", arr2)
print("arr3（指定float32类型）:\n", arr3)

# 2. 特殊数组创建（zeros/ones/empty/eye）
zeros_arr = np.zeros((3, 4), dtype=int)  # 全0数组
ones_arr = np.ones((2, 2))  # 全1数组
empty_arr = np.empty((2, 3))  # 空数组（仅分配内存）
eye_arr = np.eye(3)  # 3x3单位矩阵

print("\n全0数组:\n", zeros_arr)
print("全1数组:\n", ones_arr)
print("单位矩阵:\n", eye_arr)

# 3. 基于已有数组创建（ones_like/zeros_like）
like_arr = np.array([[1, 2], [3, 4]])
ones_like_arr = np.ones_like(like_arr)
zeros_like_arr = np.zeros_like(like_arr)
print("\n基于like_arr的全1数组:\n", ones_like_arr)

arr1（一维数组）: [1 2 3 4 5]
arr2（二维数组）:
 [[1 2 3]
 [4 5 6]]
arr3（指定float32类型）:
 [[1. 2.]
 [3. 4.]]

全0数组:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
全1数组:
 [[1. 1.]
 [1. 1.]]
单位矩阵:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

基于like_arr的全1数组:
 [[1 1]
 [1 1]]


In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int64)

print("数组维度（ndim）:", arr.ndim)  # 秩（轴的数量）
print("数组形状（shape）:", arr.shape)  # (行数, 列数)
print("数组元素总数（size）:", arr.size)  # 行数×列数
print("数据类型（dtype）:", arr.dtype)  # 元素类型
print("单个元素大小（itemsize）:", arr.itemsize)  # 字节数
print("元素实部（real）:\n", arr.real)
print("内存信息（flags）:\n", arr.flags)

数组维度（ndim）: 2
数组形状（shape）: (2, 3)
数组元素总数（size）: 6
数据类型（dtype）: int64
单个元素大小（itemsize）: 8
元素实部（real）:
 [[1 2 3]
 [4 5 6]]
内存信息（flags）:
   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [5]:
arr_int = np.array([1, 2, 3, 4])
print("原始类型:", arr_int.dtype)

# astype转换类型
arr_float = arr_int.astype(np.float64)
arr_bool = arr_int.astype(np.bool_)

print("转换为float64:", arr_float.dtype, arr_float)
print("转换为bool:", arr_bool.dtype, arr_bool)

原始类型: int64
转换为float64: float64 [1. 2. 3. 4.]
转换为bool: bool [ True  True  True  True]


In [6]:
# 1. arange：指定起始、终止、步长（不包含终止值）
arr_arange1 = np.arange(10)  # 0-9
arr_arange2 = np.arange(2, 10, 2)  # 2-8，步长2
arr_arange3 = np.arange(0, 1, 0.2)  # 浮点数步长

print("arange(10):", arr_arange1)
print("arange(2,10,2):", arr_arange2)
print("arange(0,1,0.2):", arr_arange3)

# 2. linspace：指定起始、终止、元素个数（默认包含终止值）
arr_lin = np.linspace(0, 10, 5)  # 0到10均分5个元素
arr_lin_no_end = np.linspace(0, 10, 5, endpoint=False)  # 不包含终止值

print("\nlinspace(0,10,5):", arr_lin)
print("不包含终止值:", arr_lin_no_end)

# 3. logspace：创建等比数列（默认底数10）
arr_log = np.logspace(0, 2, 5)  # 10^0到10^2，5个元素
print("\nlogspace(0,2,5):", arr_log)

arange(10): [0 1 2 3 4 5 6 7 8 9]
arange(2,10,2): [2 4 6 8]
arange(0,1,0.2): [0.  0.2 0.4 0.6 0.8]

linspace(0,10,5): [ 0.   2.5  5.   7.5 10. ]
不包含终止值: [0. 2. 4. 6. 8.]

logspace(0,2,5): [  1.           3.16227766  10.          31.6227766  100.        ]


In [7]:
# 一维数组
arr1d = np.arange(10)
print("一维数组:", arr1d)
print("索引5:", arr1d[5])
print("切片1-4（左闭右开）:", arr1d[1:5])
print("步长2切片:", arr1d[::2])

# 二维数组
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n二维数组:\n", arr2d)
print("第2行（索引1）:", arr2d[1])
print("第2列（索引1）:", arr2d[:, 1])
print("第2行第3列:", arr2d[1, 2])
print("第2列及以后:", arr2d[..., 1:])  # ...表示所有前面的维度

一维数组: [0 1 2 3 4 5 6 7 8 9]
索引5: 5
切片1-4（左闭右开）: [1 2 3 4]
步长2切片: [0 2 4 6 8]

二维数组:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
第2行（索引1）: [4 5 6]
第2列（索引1）: [2 5 8]
第2行第3列: 6
第2列及以后: [[2 3]
 [5 6]
 [8 9]]


In [8]:
# 1. 整数数组索引
arr = np.array([[1, 2], [3, 4], [5, 6]])
indices = [[0, 1, 2], [0, 1, 0]]  # 行索引[0,1,2]，列索引[0,1,0]
result1 = arr[indices]
print("整数数组索引结果:", result1)

# 2. 布尔索引
arr_bool = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
bool_mask = arr_bool > 5  # 大于5的元素为True
result2 = arr_bool[bool_mask]

print("\n布尔掩码:", bool_mask)
print("布尔索引结果:", result2)

整数数组索引结果: [[[1 2]
  [3 4]
  [5 6]]

 [[1 2]
  [3 4]
  [1 2]]]

布尔掩码: [False False False False False  True  True  True  True]
布尔索引结果: [6 7 8 9]


In [9]:
# 1. 标量与数组广播
arr = np.array([1, 2, 3, 4])
scalar = 2
result1 = arr + scalar  # 标量广播到数组每个元素
print("数组+标量:", result1)

# 2. 不同形状数组广播（满足广播规则）
arr1 = np.array([[1, 2, 3], [4, 5, 6]])  # 形状(2,3)
arr2 = np.array([1, 2, 3])  # 形状(3,)
result2 = arr1 + arr2  # arr2广播为(2,3)

print("\n(2,3)数组 + (3,)数组:\n", result2)

# 3. 不满足广播规则的示例（会报错）
try:
    arr3 = np.array([[1, 2], [3, 4]])  # 形状(2,2)
    arr4 = np.array([1, 2, 3])  # 形状(3,)
    result3 = arr3 + arr4
except ValueError as e:
    print("\n广播报错:", e)

数组+标量: [3 4 5 6]

(2,3)数组 + (3,)数组:
 [[2 4 6]
 [5 7 9]]

广播报错: operands could not be broadcast together with shapes (2,2) (3,) 


In [ ]:
常用函数：一元函

In [10]:
arr = np.array([-5.3, -6.2, -5, 0, 4.2, 5, 3, 2, 1])
print("原始数组:", arr)

# 绝对值、平方根、平方
print("绝对值（abs）:", np.abs(arr))
print("平方根（sqrt）:", np.sqrt(np.fabs(arr)))  # 先取绝对值避免负数报错
print("平方（square）:", np.square(arr))

# 指数、对数
log_arr = np.fabs(arr) + 1  # 对数输入需为正数
print("指数（exp）:", np.exp(arr[:3]))  # 仅展示前3个元素
print("自然对数（log）:", np.log(log_arr))

# 取整函数
print("向上取整（ceil）:", np.ceil(arr))
print("向下取整（floor）:", np.floor(arr))
print("四舍五入（rint）:", np.rint(arr))

# 符号函数
print("符号（sign）:", np.sign(arr))

原始数组: [-5.3 -6.2 -5.   0.   4.2  5.   3.   2.   1. ]
绝对值（abs）: [5.3 6.2 5.  0.  4.2 5.  3.  2.  1. ]
平方根（sqrt）: [2.30217289 2.48997992 2.23606798 0.         2.04939015 2.23606798
 1.73205081 1.41421356 1.        ]
平方（square）: [28.09 38.44 25.    0.   17.64 25.    9.    4.    1.  ]
指数（exp）: [0.00499159 0.00202943 0.00673795]
自然对数（log）: [1.84054963 1.97408103 1.79175947 0.         1.64865863 1.79175947
 1.38629436 1.09861229 0.69314718]
向上取整（ceil）: [-5. -6. -5.  0.  5.  5.  3.  2.  1.]
向下取整（floor）: [-6. -7. -5.  0.  4.  5.  3.  2.  1.]
四舍五入（rint）: [-5. -6. -5.  0.  4.  5.  3.  2.  1.]
符号（sign）: [-1. -1. -1.  0.  1.  1.  1.  1.  1.]


In [11]:
arr1 = np.array([1, 2, 8, 1])
arr2 = np.array([4, 5, 6, 0])

print("数组1:", arr1)
print("数组2:", arr2)

# 加法、乘法、取模
print("元素相加（add）:", np.add(arr1, arr2))
print("元素相乘（multiply）:", np.multiply(arr1, arr2))
print("取模（mod）:", np.mod(arr2, arr1))

# 点积（矩阵乘法）
print("点积（dot）:", np.dot(arr1, arr2))

# 比较函数
print("大于（greater）:", np.greater(arr1, arr2))
print("等于（equal）:", np.equal(arr1, arr2))

# 逻辑函数
print("逻辑与（logical_and）:", np.logical_and(arr1, arr2))
print("逻辑或（logical_or）:", np.logical_or(arr1, arr2))

数组1: [1 2 8 1]
数组2: [4 5 6 0]
元素相加（add）: [ 5  7 14  1]
元素相乘（multiply）: [ 4 10 48  0]
取模（mod）: [0 1 6 0]
点积（dot）: 62
大于（greater）: [False False  True  True]
等于（equal）: [False False False False]
逻辑与（logical_and）: [ True  True  True False]
逻辑或（logical_or）: [ True  True  True  True]


In [12]:
# 一维数组统计
arr1d = np.array([1, 2, 3, 4, 5])
print("一维数组:", arr1d)
print("平均值（mean）:", np.mean(arr1d))
print("中位数（median）:", np.median(arr1d))
print("标准差（std）:", np.std(arr1d))
print("方差（var）:", np.var(arr1d))
print("最大值（max）:", np.max(arr1d))
print("最小值（min）:", np.min(arr1d))
print("最大值索引（argmax）:", np.argmax(arr1d))
print("最小值索引（argmin）:", np.argmin(arr1d))

# 二维数组统计（指定轴）
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n二维数组:\n", arr2d)
print("每列平均值（axis=0）:", np.mean(arr2d, axis=0))
print("每行最大值（axis=1）:", np.max(arr2d, axis=1))

一维数组: [1 2 3 4 5]
平均值（mean）: 3.0
中位数（median）: 3.0
标准差（std）: 1.4142135623730951
方差（var）: 2.0
最大值（max）: 5
最小值（min）: 1
最大值索引（argmax）: 4
最小值索引（argmin）: 0

二维数组:
 [[1 2 3]
 [4 5 6]]
每列平均值（axis=0）: [2.5 3.5 4.5]
每行最大值（axis=1）: [3 6]
